// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWTQPS-1nx8KbYiWdRCmUGyTFwTEJx-2s',
    appId: '1:38228217910:web:c0f627f9e0b491b9830897',
    messagingSenderId: '38228217910',
    projectId: 'handylink-1588f',
    authDomain: 'handylink-1588f.firebaseapp.com',
    storageBucket: 'handylink-1588f.firebasestorage.app',
    measurementId: 'G-HPMLJNWQF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBdnuWqID3HzKtwXG85-BXo4HgcHdlLA4',
    appId: '1:38228217910:android:c1a551dde32c1182830897',
    messagingSenderId: '38228217910',
    projectId: 'handylink-1588f',
    storageBucket: 'handylink-1588f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfFbKbXKafrZUzUt2G3qHd95jK6vDADKM',
    appId: '1:38228217910:ios:59782553c4af8157830897',
    messagingSenderId: '38228217910',
    projectId: 'handylink-1588f',
    storageBucket: 'handylink-1588f.firebasestorage.app',
    iosBundleId: 'com.example.handyLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfFbKbXKafrZUzUt2G3qHd95jK6vDADKM',
    appId: '1:38228217910:ios:59782553c4af8157830897',
    messagingSenderId: '38228217910',
    projectId: 'handylink-1588f',
    storageBucket: 'handylink-1588f.firebasestorage.app',
    iosBundleId: 'com.example.handyLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWTQPS-1nx8KbYiWdRCmUGyTFwTEJx-2s',
    appId: '1:38228217910:web:f6623b0c5b3c3f80830897',
    messagingSenderId: '38228217910',
    projectId: 'handylink-1588f',
    authDomain: 'handylink-1588f.firebaseapp.com',
    storageBucket: 'handylink-1588f.firebasestorage.app',
    measurementId: 'G-MNY00GZK7Q',
  );
}
