// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// ---
/// This file is auto-generated by the FlutterFire CLI. It acts as a centralized 
/// configuration file that holds platform-specific Firebase details (like Apple `bundleId`, 
/// Android `appId`, and various `apiKey`s). 
/// 
/// These keys uniquely identify this app to the Firebase backend. For client-side Firebase apps, 
/// it is normal for these keys to be bundled in the source code; security is enforced via 
/// Firebase App Check and Firestore Security Rules on the backend rather than by hiding the keys.
class DefaultFirebaseOptions {
  /// Dynamically returns the correct [FirebaseOptions] depending on the 
  /// platform the app is currently executing on (e.g., Web, Android, iOS).
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Firebase configuration options specific to the Web platform.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWTQPS-1nx8KbYiWdRCmUGyTFwTEJx-2s',
    appId: '1:38228217910:web:c0f627f9e0b491b9830897',
    messagingSenderId: '38228217910',
    projectId: 'handylink-1588f',
    authDomain: 'handylink-1588f.firebaseapp.com',
    storageBucket: 'handylink-1588f.firebasestorage.app',
    measurementId: 'G-HPMLJNWQF6',
  );

  /// Firebase configuration options specific to the Android platform.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBdnuWqID3HzKtwXG85-BXo4HgcHdlLA4',
    appId: '1:38228217910:android:c1a551dde32c1182830897',
    messagingSenderId: '38228217910',
    projectId: 'handylink-1588f',
    storageBucket: 'handylink-1588f.firebasestorage.app',
  );

  /// Firebase configuration options specific to the iOS platform.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfFbKbXKafrZUzUt2G3qHd95jK6vDADKM',
    appId: '1:38228217910:ios:59782553c4af8157830897',
    messagingSenderId: '38228217910',
    projectId: 'handylink-1588f',
    storageBucket: 'handylink-1588f.firebasestorage.app',
    iosBundleId: 'com.example.handyLink',
  );

  /// Firebase configuration options specific to the macOS platform.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfFbKbXKafrZUzUt2G3qHd95jK6vDADKM',
    appId: '1:38228217910:ios:59782553c4af8157830897',
    messagingSenderId: '38228217910',
    projectId: 'handylink-1588f',
    storageBucket: 'handylink-1588f.firebasestorage.app',
    iosBundleId: 'com.example.handyLink',
  );

  /// Firebase configuration options specific to the Windows platform.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWTQPS-1nx8KbYiWdRCmUGyTFwTEJx-2s',
    appId: '1:38228217910:web:f6623b0c5b3c3f80830897',
    messagingSenderId: '38228217910',
    projectId: 'handylink-1588f',
    authDomain: 'handylink-1588f.firebaseapp.com',
    storageBucket: 'handylink-1588f.firebasestorage.app',
    measurementId: 'G-MNY00GZK7Q',
  );
}
